# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Locu < Formula
  desc ""
  homepage "https://github.com/LocuCode/LocuCLI"
  version "0.1"

  on_macos do
    url "https://github.com/LocuCode/LocuCLI/releases/download/v0.1/askcloudhelloworld_0.1_darwin_all.tar.gz"
    sha256 "5d44eb6b6ef56a429a16c42d5795f0ad22a5e343a7f0e7578ab54ead3f173749"

    def install
      bin.install "locu"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LocuCode/LocuCLI/releases/download/v0.1/askcloudhelloworld_0.1_linux_arm64.tar.gz"
      sha256 "eca7fafceca46d9a81e7f8f20d52c34a4558c2c8a8ecf4dafb93354d427cf0ed"

      def install
        bin.install "locu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/LocuCode/LocuCLI/releases/download/v0.1/askcloudhelloworld_0.1_linux_amd64.tar.gz"
      sha256 "d9969013e84e549bae888b2025b16cef240840b3ea2a61676ce8a22411e17751"

      def install
        bin.install "locu"
      end
    end
  end
end
