# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Locu < Formula
  desc ""
  homepage "https://github.com/LocuCode/LocuCLI"
  version "1.4"

  on_macos do
    url "https://github.com/LocuCode/LocuCLI/releases/download/v1.4/LocuCLI_1.4_darwin_all.tar.gz"
    sha256 "454dda1cd418137b2ffbb699d0afa2a8d1155accb1cff416d80674f830badcbb"

    def install
      bin.install "LocuCLI"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LocuCode/LocuCLI/releases/download/v1.4/LocuCLI_1.4_linux_arm64.tar.gz"
      sha256 "1ccfc9a9a848800164be98552466bc95650facfbb562df59d9cb2a21d3c8b7e7"

      def install
        bin.install "locu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/LocuCode/LocuCLI/releases/download/v1.4/LocuCLI_1.4_linux_amd64.tar.gz"
      sha256 "538609145053fe80a0d040579163372e0c77f6c4f582207827f0ba10b5d14873"

      def install
        bin.install "locu"
      end
    end
  end
end
