# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mediumautopost < Formula
  desc ""
  homepage "https://github.com/askcloudarchitech/mediumautopost"
  version "0.6"

  on_macos do
    url "https://github.com/askcloudarchitech/mediumautopost/releases/download/v0.6/mediumautopost_0.6_darwin_all.tar.gz"
    sha256 "1329ae7e0cde88d6f9bfb9ac226f77e195b65a612e33c64490eaa8c91efe7fd8"

    def install
      bin.install "mediumautopost"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/askcloudarchitech/mediumautopost/releases/download/v0.6/mediumautopost_0.6_linux_amd64.tar.gz"
      sha256 "0ec1db18f8097a78f05cadcfcfadb6f25cde855d4b5982575d1b5037282c0cef"

      def install
        bin.install "mediumautopost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/askcloudarchitech/mediumautopost/releases/download/v0.6/mediumautopost_0.6_linux_arm64.tar.gz"
      sha256 "f28443a121626bc179f7aaa39d1400a8cd7ea07df9329e38573b56cedc2f3d11"

      def install
        bin.install "mediumautopost"
      end
    end
  end
end
