# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mediumautopost < Formula
  desc ""
  homepage "https://github.com/askcloudarchitech/mediumautopost"
  version "0.3"

  on_macos do
    url "https://github.com/askcloudarchitech/mediumautopost/releases/download/v0.3/mediumautopost_0.3_darwin_all.tar.gz"
    sha256 "d3164ffd9ee069b99b37692fd409ffd9ee4dad8cc7b63589c01728c1d289b7c0"

    def install
      bin.install "mediumautopost"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/askcloudarchitech/mediumautopost/releases/download/v0.3/mediumautopost_0.3_linux_arm64.tar.gz"
      sha256 "0bbad64c2035652ae50d83ab36de5f64397443816fef0cea81f8a9130f392b5a"

      def install
        bin.install "mediumautopost"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/askcloudarchitech/mediumautopost/releases/download/v0.3/mediumautopost_0.3_linux_amd64.tar.gz"
      sha256 "f28cec5b6ce3eb20aaac7695293ace924bba52c6fc0232c9245ca486d859ecc6"

      def install
        bin.install "mediumautopost"
      end
    end
  end
end
